name: Release

permissions: write-all

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.4.2
      env:
        CI: false
    - name: install dependencies
      run: npm install
    - name: build-react
      run: npm run build
    - name: mix
      run: npm run mix
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run publish